services:
  nginx-server:
    build:
      context: .
    image: nginx-https:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./html:/var/www/html/
